# Generated by Django 2.2.7 on 2019-11-21 06:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20191121_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
        migrations.AddField(
            model_name='board',
            name='image_thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='boards/test3'),
        ),
    ]
