# Generated by Django 2.2.7 on 2019-11-21 07:04

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20191121_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to='boards/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='board',
            name='image_thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='boards/test3'),
        ),
    ]
