# Generated by Django 2.2.7 on 2019-11-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20191121_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image_thumb',
        ),
    ]
