# Generated by Django 2.2.7 on 2019-11-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subway', '0002_delete_subway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('bread', models.CharField(max_length=20)),
                ('vegetable', models.CharField(max_length=20)),
                ('sauce', models.CharField(max_length=20)),
                ('drink', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
