# Generated by Django 2.2.7 on 2019-11-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_subway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subway',
            old_name='date',
            new_name='nowdate',
        ),
    ]
