# Generated by Django 2.2.7 on 2019-11-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btest',
            name='btest_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='btestchild',
            name='btestchild_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
