# Generated by Django 2.2.7 on 2019-11-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0002_auto_20191119_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='btestchild',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
